upstream backend {
    server localhost:8081 fail_timeout=30s max_fails=3;
    server localhost:8082 fail_timeout=30s max_fails=3;
}

server {
    listen       80;
    server_name  url-shortener.sabihinmolang.eu.org;

    location / {
        proxy_pass http://backend;
	    proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


server {
    listen 80 default_server;
    server_name _; # The underscore is a wildcard for "everything else"

    # Option A: Close the connection immediately (No response)
    return 444; 

    # Option B: Standard "Forbidden" error
    # return 403;
}